Refactoring Code based on Design and Implementation Smells
TimefoldAI/timefold-quickstarts pull request #170
Opened 2023-11-28 03:56 UTC by nisarrg

2023-11-28 03:57 UTC, nisarrg commented
Fixing Code Smells in the code.

2023-11-28 07:01 UTC, triceo requested changes
Thank you for the PR, @nisarrg!
I am requesting some changes to be made before we can merge it.

2023-11-28 07:01 UTC, triceo commented on technology/java-spring-boot/src/main/java/org/acme/schooltimetabling/solver/TimeTableConstraintProvider.java
> +    //TODO --> tool detected this as long statement, it is technically not : FP
Please remove the comment.

2023-11-28 07:01 UTC, triceo commented on technology/java-spring-boot/src/main/java/org/acme/schooltimetabling/solver/TimeTableConstraintProvider.java
> +    //TODO ---> removed magic number and introduced global variable : TP
Please remove the comment.

2023-11-28 07:01 UTC, triceo commented on technology/java-spring-boot/src/main/java/org/acme/schooltimetabling/solver/TimeTableConstraintProvider.java
> +    //TODO ---> removed magic number and introduced global variable : TP
Please remove the comment.

2023-11-28 07:01 UTC, triceo commented on use-cases/maintenance-scheduling/src/main/java/org/acme/maintenancescheduling/domain/MaintenanceSchedule.java
> +    //TODO --> Never used Constructor.
Please remove the comment. The constructor is required for Timefold to function, even though it seems unused.

2023-11-28 07:01 UTC, triceo commented on use-cases/maintenance-scheduling/src/main/java/org/acme/maintenancescheduling/domain/MaintenanceSchedule.java
> +//    }
Why was this removed? I do not see it being replaced by anything.

2023-11-28 07:01 UTC, triceo commented on use-cases/vehicle-routing-capacity/src/main/java/org/acme/vehiclerouting/rest/VehicleRouteDemoResource.java
> +        final private Location northEastCorner;
Please use `private final`, not `final private`.

2023-11-28 07:01 UTC, triceo commented on use-cases/vehicle-routing-time-windows/src/main/java/org/acme/vehiclerouting/rest/VehicleRouteDemoResource.java
> +        // TODO --> these variables will be final : FN
Please remove the comment.

2023-11-28 07:01 UTC, triceo commented on technology/java-spring-boot/src/main/java/org/acme/schooltimetabling/TimeTableSpringBootApp.java
> +// TODO --> unutilised abstraction --> main file : FP
Please remove the comment.

2023-11-28 07:02 UTC, triceo commented on technology/java-spring-boot/src/main/java/org/acme/schooltimetabling/persistence/TimeTableRepository.java
> +    // TODO --> SINGLETON_TIME_TABLE_ID is public : deficient encapsulation --> TP
Please remove the comment.

2023-11-28 07:02 UTC, triceo commented
Also, please open the PR against the `development` branch. We do not merge any changes to `stable` branch.

2023-12-12 14:40 UTC, triceo commented
Closing on account of no response.
Please reopen if you intend to keep working on it.

2023-12-12 14:40 UTC, closed without merging