fix: Removing database support of Employee Scheduling
TimefoldAI/timefold-quickstarts pull request #316
Opened 2024-03-01 13:26 UTC by zepfred

## Description of the change

This PR removes the database support for the `Employee Scheduling` quick start.

![Screenshot from 2024-03-01 10-03-28](https://github.com/TimefoldAI/timefold-quickstarts/assets/11961659/eb87ed04-0ac7-4fce-9702-7561c7b85b63)
![Screenshot from 2024-03-01 10-04-41](https://github.com/TimefoldAI/timefold-quickstarts/assets/11961659/292947dc-eec4-4d37-ae04-4280dd674c07)
![Screenshot from 2024-03-01 10-03-33](https://github.com/TimefoldAI/timefold-quickstarts/assets/11961659/ea71e795-5999-4b73-9db9-6ad37cd0f2ce)
![Screenshot from 2024-03-01 10-04-12](https://github.com/TimefoldAI/timefold-quickstarts/assets/11961659/ae2c878e-26c3-4053-b069-e015897565d6)
![Screenshot from 2024-03-01 10-04-26](https://github.com/TimefoldAI/timefold-quickstarts/assets/11961659/f03f3240-ecba-4430-9d50-ff2f1ea27716)
![Screenshot from 2024-03-01 10-04-20](https://github.com/TimefoldAI/timefold-quickstarts/assets/11961659/bdfc85e1-88f4-4ca0-975f-0a6e0d5a479e)

## Checklist

### Development

- [x] The changes have been covered with tests, if necessary.
- [x] You have a green build, with the exception of the flaky tests.
- [x] UI and JS files are fully tested, the user interface works for all modules affected by your changes (e.g., solve and analyze buttons).
- [x] The network calls work for all modules affected by your changes (e.g., solving a problem).
- [x] The console messages are validated for all modules affected by your changes.

### Code Review

- [x] This pull request includes an explanatory title and description.
- [x] The GitHub issue is linked.
- [ ] At least one other engineer has approved the changes.
- [ ] After PR is merged, inform the reporter.

2024-03-03 11:25 UTC, triceo requested changes
Something is wrong with the constraints. See that the score is 0/0, yet there are clearly broken constraints.

![image](https://github.com/TimefoldAI/timefold-quickstarts/assets/247403/be3e4c33-5184-46e2-a52c-c5c30cee6f7d)

2024-03-04 12:27 UTC, zepfred commented
> Something is wrong with the constraints. See that the score is 0/0, yet there are clearly broken constraints.
> 
> ![image](https://private-user-images.githubusercontent.com/247403/309545903-be3e4c33-5184-46e2-a52c-c5c30cee6f7d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NDk0ODYsIm5iZiI6MTcwOTU0OTE4NiwicGF0aCI6Ii8yNDc0MDMvMzA5NTQ1OTAzLWJlM2U0YzMzLTUxODQtNDZlMi1hNTJjLWM1YzMwY2VlNmY3ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNFQxMDQ2MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mY2JlYjlkN2U4MDc3MDYzMTdmZjY0NjllZThhZWRkMjRmYjU3YjVlYTllZjEwM2RmMzJjMDYzYTAyZGI3NTAyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lBwVvHsWRnCnau1U1DNSwDH81K5okyg9uIi517LfOcI)

Good catch! When using JPA, the persistence context ensures that there will be single instances of `Employee`, and they will be equal to `Joiners.equal(Shift::getEmployee, Availability::getEmployee)`. I had to add the `equals` and `hashCode` methods to compare the instances properly.

![Screenshot from 2024-03-04 09-26-32](https://github.com/TimefoldAI/timefold-quickstarts/assets/11961659/e04fa1a6-29c4-408b-85e2-349b5be9cea0)

2024-03-04 12:43 UTC, triceo commented on use-cases/employee-scheduling/src/main/java/org/acme/employeescheduling/domain/Availability.java
> +        return Objects.hash(getId());
Let's not use [Objects.hash(...)](https://docs.oracle.com/javase/8/docs/api/java/util/Objects.html#hash-java.lang.Object...-).

This method creates a varargs array every time it is invoked. When this `hashCode` method gets on a hot path (such as in constraints), this is a considerable slowdown.

Let's not teach people this.

2024-03-04 13:02 UTC, triceo approved these changes

2024-03-04 15:33 UTC, triceo approved these changes

2024-03-04 15:41 UTC, merged