chore: Improve the release pipeline
TimefoldAI/timefold-quickstarts pull request #601
Opened 2024-10-08 14:58 UTC by zepfred

2024-10-08 15:42 UTC, triceo commented on .github/workflows/release.yml
> +          if [ -n "$exists" ]; then
Why are we doing this if none of workflows in the other repos had this?
Can't we delete the branch if it exists, like we do everywhere else? For consistency.

2024-11-26 06:50 UTC, triceo requested changes
I'm not sure this file is valid, or I don't understand the `'` syntax.
Also, we switched to a new way of publishing Maven Central artifacts, and so the release pipeline will have to be updated more.

Let's discuss.

2024-11-26 06:50 UTC, triceo commented on .github/workflows/release.yml
> +'name: Release
?

2024-11-26 09:51 UTC, zepfred commented on .github/workflows/release.yml
> +'name: Release
This is a typo

2024-11-26 09:58 UTC, zepfred commented
> I'm not sure this file is valid, or I don't understand the `'` syntax. Also, we switched to a new way of publishing Maven Central artifacts, and so the release pipeline will have to be updated more.
> 
> Let's discuss.

We create a branch named `release_branch_...`, which contains changes related to the release version. Next, we will create a pull request and merge all changes from the release branch into the stable branch. The final three steps are to move the release branch back to `999-dev`, check if the version branch (`v1.16.x`) exists, and rename the release branch to the version branch instead of deleting it.

2024-11-26 10:24 UTC, triceo approved these changes

2024-11-26 10:24 UTC, merged